### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by ducha-aiki** [sailor-z/CLNet#1]

**Comment by sailor-z** [comment]
Hi Dmytro,

The code is going to be released next week.

**Comment by ducha-aiki** [comment]
Thank you a lot! May I also ask you for the some kind of demo.py to have a blessed way of running the network?
Like https://github.com/zjhthu/OANet/blob/master/demo/demo.py

**Comment by sailor-z** [comment]
Of course. I'll add a demo.py soon.

**Comment by sailor-z** [comment]
The demo.py has been uploaded.

**Comment by ducha-aiki** [comment]
Thank you a lot!
