### ISSUE TITLE
No module named 'dataset'

### ISSUE THREAD

**Issue by weitong8591** [sailor-z/CLNet#4]
Hello! Thanks for sharing the code. Where is this 'dataset' package?
https://github.com/sailor-z/CLNet/blob/2dc7a6900b8fec6e9e584feeca233d7c1e2f7a3b/dump_match/yfcc.py#L2

**Comment by sailor-z** [comment]
Hi, 'dataset.py' has been uploaded. Sorry for the mistake.

**Comment by weitong8591** [comment]
It's okay. Thanks.
